language: java
sudo: required
jdk:
  - oraclejdk8
dist: trusty
before_script:
  - chmod +x gradlew
script:
  - ./gradlew check
  - ./gradlew codeCoverageReport
install:
  - ./gradlew build
after_success:
  - CODECOV_TOKEN="5e227cfb-68c7-4a31-8cf5-0d1b0e1f2225"
  - bash <(curl -s https://codecov.io/bash)